-- 외래키 생성
ALTER TABLE video_post
ADD CONSTRAINT fk_thumbnail_file_id -- 외래키 이름(자유 지정)
FOREIGN KEY (thumbnail_file_id)
REFERENCES file_meta(id);

-----------------------------------------------------------

-- 테이블 생성 SQL - video_post

CREATE TABLE video_post
(
    id                   bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                varchar(255)    NOT NULL,
    video_id             varchar(500)    NOT NULL,
    thumbnail_file_id    bigint          NOT NULL,
    content              text            NULL,
    created_at           timestamp       NOT NULL,
    updated_at          timestamp       NOT NULL,
    PRIMARY KEY (id)
);

-- 테이블 Comment 설정 SQL - video_post
COMMENT ON TABLE video_post IS '영상 게시글';

-- 컬럼 Comment 설정 SQL - video_post.id
COMMENT ON COLUMN video_post.id IS '게시글 아이디. 고유 식별자';

-- 컬럼 Comment 설정 SQL - video_post.title
COMMENT ON COLUMN video_post.title IS '제목. 게시글 제목';

-- 컬럼 Comment 설정 SQL - video_post.video_id
COMMENT ON COLUMN video_post.video_id IS '영상 ID. 유튜브 영상 고유 ID, 전체 URL의 마지막 경로에서 추출한 값';

-- 컬럼 Comment 설정 SQL - video_post.thumbnail_file_id
COMMENT ON COLUMN video_post.thumbnail_file_id IS '썸네일 이미지 ID. 썸네일 이미지 파일 ID (file_meta 참조)';

-- 컬럼 Comment 설정 SQL - video_post.content
COMMENT ON COLUMN video_post.content IS '내용. 작성 내용';

-- 컬럼 Comment 설정 SQL - video_post.created_at
COMMENT ON COLUMN video_post.created_at IS '생성 일시. 생성 일시';

-- 컬럼 Comment 설정 SQL - video_post.updated_at
COMMENT ON COLUMN video_post.updated_at IS '수정 일시. 수정 일시';

-----------------------------------------------------------

-- 테이블 생성 SQL - file_meta
CREATE TABLE file_meta
(
    id               bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_name    varchar(255)    NOT NULL,
    saved_name       varchar(255)    NOT NULL,
    content_type     varchar(100)    NOT NULL,
    size             bigint          NOT NULL,
    path             varchar(500)    NOT NULL,
    created_at       timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

-- 테이블 Comment 설정 SQL - file_meta
COMMENT ON TABLE file_meta IS '파일 메타 정보';

-- 컬럼 Comment 설정 SQL - file_meta.id
COMMENT ON COLUMN file_meta.id IS '파일 아이디. 고유 식별자';

-- 컬럼 Comment 설정 SQL - file_meta.original_name
COMMENT ON COLUMN file_meta.original_name IS '원본 파일명. 사용자가 업로드한 파일명';

-- 컬럼 Comment 설정 SQL - file_meta.saved_name
COMMENT ON COLUMN file_meta.saved_name IS '저장 파일명. 서버에 저장된 실제 파일명 (UUID 포함)';

-- 컬럼 Comment 설정 SQL - file_meta.content_type
COMMENT ON COLUMN file_meta.content_type IS 'MIME 타입. image/png, application/pdf 등 콘텐츠 타입';

-- 컬럼 Comment 설정 SQL - file_meta.size
COMMENT ON COLUMN file_meta.size IS '파일 크기. 파일 크기(byte 단위)';

-- 컬럼 Comment 설정 SQL - file_meta.path
COMMENT ON COLUMN file_meta.path IS '저장 경로. 로컬/스토리지 저장 경로';

-- 컬럼 Comment 설정 SQL - file_meta.created_at
COMMENT ON COLUMN file_meta.created_at IS '생성 일시. 파일 업로드 시각';