-- 테이블 생성 SQL - file_meta
CREATE TABLE file_meta
(
    id               bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_name    varchar(255)    NOT NULL,
    saved_name       varchar(255)    NOT NULL,
    content_type     varchar(100)    NOT NULL,
    size             bigint          NOT NULL,
    path             varchar(500)    NOT NULL,
    created_at       timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

-- 테이블 Comment 설정 SQL - file_meta
COMMENT ON TABLE file_meta IS '파일 메타 정보';

-- 컬럼 Comment 설정 SQL - file_meta.id
COMMENT ON COLUMN file_meta.id IS '파일 아이디. 고유 식별자';

-- 컬럼 Comment 설정 SQL - file_meta.original_name
COMMENT ON COLUMN file_meta.original_name IS '원본 파일명. 사용자가 업로드한 파일명';

-- 컬럼 Comment 설정 SQL - file_meta.saved_name
COMMENT ON COLUMN file_meta.saved_name IS '저장 파일명. 서버에 저장된 실제 파일명 (UUID 포함)';

-- 컬럼 Comment 설정 SQL - file_meta.content_type
COMMENT ON COLUMN file_meta.content_type IS 'MIME 타입. image/png, application/pdf 등 콘텐츠 타입';

-- 컬럼 Comment 설정 SQL - file_meta.size
COMMENT ON COLUMN file_meta.size IS '파일 크기. 파일 크기(byte 단위)';

-- 컬럼 Comment 설정 SQL - file_meta.path
COMMENT ON COLUMN file_meta.path IS '저장 경로. 로컬/스토리지 저장 경로';

-- 컬럼 Comment 설정 SQL - file_meta.created_at
COMMENT ON COLUMN file_meta.created_at IS '생성 일시. 파일 업로드 시각';